import { Inter } from "next/font/google";
import "../globals.css";
import SidebarNav from "@/components/SidebarNav";
import ResponsiveAppBar from "@/components/ResponsiveAppBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ResponsiveAppBar />
        <div className="flex">
          <SidebarNav />
          {children}
        </div>
      </body>
    </html>
  );
}
